// fixtures/playground-vue/src/client/App.vue
<script setup lang="ts">
import { computed, inject, ref } from 'vue';

import DeferredPage from './DeferredPage.vue';
import HomePage from './HomePage.vue';
import StreamingPage from './StreamingPage.vue';
import { PLAYGROUND_KEY } from './setup-app';

const props = defineProps<{ location?: string }>();

// Server passes `location`; on the client fall back to the current path so hydration matches.
const path = computed(() => props.location ?? (typeof window !== 'undefined' ? window.location.pathname : '/'));
const isStreaming = computed(() => path.value.startsWith('/streaming'));
const isDeferred = computed(() => path.value.startsWith('/deferred'));

// Provided by setupApp on both server and client — presence proves the hook ran on this path.
const playgroundName = inject(PLAYGROUND_KEY, 'no-setup-app');

// Proves hydration by EXECUTED BEHAVIOUR rather than markup: the server renders `count: 0`, and
// only a hydrated, interactive root can turn a click into `count: 1`.
const count = ref(0);
</script>

<template>
  <main class="app">
    <h1>
      τjs Vue playground <small>(setupApp: {{ playgroundName }})</small>
    </h1>
    <nav><a href="/">/ (ssr)</a> · <a href="/streaming">/streaming</a> · <a href="/deferred">/deferred</a></nav>

    <button id="counter" type="button" @click="count += 1">count: {{ count }}</button>

    <Suspense v-if="isDeferred">
      <template #default>
        <DeferredPage />
      </template>
      <template #fallback>
        <p id="reviews-pending">loading reviews</p>
      </template>
    </Suspense>
    <Suspense v-else-if="isStreaming">
      <template #default>
        <StreamingPage />
      </template>
      <template #fallback>
        <p class="fallback">Streaming… waiting on the server.</p>
      </template>
    </Suspense>
    <HomePage v-else />
  </main>
</template>

// fixtures/playground-react/src/client/App.tsx
import React, { Suspense, useState } from 'react';
import { createDeferredAccessor, useSSRStore } from '@taujs/react';

import type { DeferredRouteData } from '../server/routes/deferred.ts';

/**
 * RFC 0007: the ROUTE-DECLARED deferred read.
 *
 * The accessor is typed from the route config alone - `DeferredDataOf<typeof deferredRoute>` - so
 * the payload shape is never re-declared here. The component starts nothing: the host began this
 * work before the render, and `useDeferred` only projects the named promise onto React's own
 * `use()`, suspending this boundary and nothing else.
 */
const useDeferred = createDeferredAccessor<DeferredRouteData>();

function DeferredReviews() {
  const reviews = useDeferred('reviews');
  // The annotation is the GATE: `count` is inferred from the route's `serviceData()` brand, so
  // changing the service's declared result type fails this typecheck rather than shipping.
  const count: number = reviews.count;

  return <p id="reviews">{`reviews: ${count} - ${reviews.top}`}</p>;
}

/**
 * Proves hydration by EXECUTED BEHAVIOUR rather than markup: the server renders `count: 0`, and
 * only a hydrated, interactive root can turn a click into `count: 1`.
 */
function Counter() {
  const [count, setCount] = useState(0);

  return (
    <button id="counter" type="button" onClick={() => setCount((n) => n + 1)}>
      count: {count}
    </button>
  );
}

export const App = ({ location = '' }: { location?: string }) => {
  const data = useSSRStore<Record<string, unknown>>();

  return (
    <main>
      <h1>τjs playground</h1>
      <p>Fixture app for the introspection substrate. Initial data below.</p>
      <Counter />
      <pre id="initial-data">{JSON.stringify(data, null, 2)}</pre>

      {location.startsWith('/deferred') ? (
        <Suspense fallback={<p id="reviews-pending">loading reviews</p>}>
          <DeferredReviews />
        </Suspense>
      ) : null}
    </main>
  );
};
