// packages/solid/src/SSRHydration.ts
import { hydrate, render } from 'solid-js/web';

import { createSSRStore, provideSSRStore } from './SSRDataStore.js';
import { createUILogger } from './utils/Logger.js';

import type { JSX } from 'solid-js';
import type { SolidLogger } from './utils/Logger.js';

/**
 * Client-side bootstrap for a τjs Solid app, and its hydration-observability surface.
 *
 * The lifecycle callbacks are ADVISORY observers of one `hydrateApp` invocation:
 * - `onStart` fires once when application hydration begins (hydrate path only), after the
 *   `hydration:start` beacon and before the native `hydrate`.
 * - `onSuccess` fires once when the framework establishes the application root - a successful return
 *   from Solid's `hydrate(...)` on the hydrate path, or `render(...)` on the CSR-fallback path. It
 *   does NOT mean every resource or `<Suspense>` boundary settled.
 * - `onHydrationError` fires once for a failed root establishment (a synchronous hydrate/render
 *   throw, or a missing root element).
 *
 * Exactly one of `onSuccess` | `onHydrationError` settles per invocation; each fires at most once.
 * The internal τjs hydration beacons are hydration-only and always precede the corresponding user
 * observer.
 */
export type HydrateAppOptions = {
  app: (props: { location: string }) => JSX.Element;
  /**
   * Must match the `renderId` the SERVER rendered this root with - it is the shared deterministic
   * namespace for Solid's markers and serialised data (design 4). A mismatch means the client
   * cannot find the server's markers.
   */
  renderId?: string;
  rootElementId?: string;
  /** Receives hydration lifecycle logs. A Pino/server-shaped or UI-shaped logger; see `SolidLogger`. */
  logger?: SolidLogger;
  /** Gate verbose start/success/CSR lifecycle logs. Warnings and errors are never gated. Default `false`. */
  enableDebug?: boolean;
  /** Observes the start of application hydration (hydrate path only). */
  onStart?: () => void;
  /** Observes successful root establishment (hydrate or CSR). */
  onSuccess?: () => void;
  /** Observes a failed root establishment. */
  onHydrationError?: (error: unknown) => void;
};

/** The dev-only introspection beacon, set by the server-injected dev script and never by users. */
type TaujsDevtoolsHook = { emit?: (event: 'hydration:start' | 'hydration:success' | 'hydration:error', payload?: unknown) => void };

const emitBeacon = (event: 'hydration:start' | 'hydration:success' | 'hydration:error', payload?: unknown): void => {
  try {
    (window as { __TAUJS_DEVTOOLS_HOOK__?: TaujsDevtoolsHook }).__TAUJS_DEVTOOLS_HOOK__?.emit?.(event, payload);
  } catch {
    // the beacon must never affect hydration
  }
};

export function hydrateApp({
  app,
  renderId,
  rootElementId = 'root',
  logger,
  enableDebug = false,
  onStart,
  onSuccess,
  onHydrationError,
}: HydrateAppOptions): void {
  // `logger ?? console`: with no supplied logger, warnings/errors fall back to `console.warn`/
  // `console.error` (parity with @taujs/react and @taujs/vue), while verbose lifecycle logging stays
  // gated by `enableDebug`. This only shapes the client hydration seam - `createUILogger`'s
  // server-path defaults are unchanged.
  const { log, error } = createUILogger(logger ?? console, { debugCategory: 'ssr', context: { scope: 'solid-hydration' }, enableDebug });

  // Advisory observer isolation: a callback throw is logged and swallowed - it is never fed to
  // `onHydrationError`, never manufactures a beacon, and never tears down the root it observes.
  const runObserver = (label: string, run: () => void) => {
    try {
      run();
    } catch (cbErr) {
      error(`Hydration ${label} callback threw (ignored):`, cbErr);
    }
  };

  // Beacon policy: the hydrate path emits `hydration:*` beacons; the CSR-fallback path emits none (a
  // CSR mount is not a hydration). Set once when the path is chosen, read by the report helpers.
  let emitBeacons = false;

  // Single settlement: exactly one of `onSuccess` | `onHydrationError`, each at most once. Solid's
  // `hydrate`/`render` return synchronously, so success is reported inline after the native call -
  // but the guard is explicit so a later edit cannot produce success followed by failure. `onStart`
  // is hydration-only and, running once per invocation, fires at most once.
  let settled = false;

  // Verbose lifecycle logs (`log`) are gated by `enableDebug` inside `createUILogger`; warnings and
  // errors are never gated. There is one gate, in the logger adapter - the calls here are
  // unconditional so gating cannot drift between the two.
  const reportStart = () => {
    log('Hydration started');
    if (emitBeacons) emitBeacon('hydration:start');
    runObserver('onStart', () => onStart?.());
  };

  const reportSuccess = (message: string) => {
    if (settled) return;
    settled = true;
    log(message);
    if (emitBeacons) emitBeacon('hydration:success');
    runObserver('onSuccess', () => onSuccess?.());
  };

  const reportFailure = (message: string, err: unknown) => {
    if (settled) return;
    settled = true;
    error(message, err);
    if (emitBeacons) emitBeacon('hydration:error', err);
    runObserver('onHydrationError', () => onHydrationError?.(err));
  };

  const bootstrap = () => {
    const rootElement = document.getElementById(rootElementId);

    if (!rootElement) {
      // A missing root is a bootstrap failure: emit an error beacon with no preceding `start`, and
      // report through the single failure path (design 4 / react + vue precedent).
      emitBeacons = true;
      reportFailure(`taujs: root element with id "${rootElementId}" not found`, new Error(`taujs: root element with id "${rootElementId}" not found`));

      return;
    }

    const initialData = (window as { __INITIAL_DATA__?: Record<string, unknown> }).__INITIAL_DATA__;
    const location = window.location.pathname + window.location.search;

    // Missing initial data falls back to CSR (design 4): a CSR mount is NOT a hydration, so it emits
    // no beacon and no `onStart`. A successful CSR root establishment still reports `onSuccess`; a
    // failed one reports `onHydrationError`.
    if (initialData === undefined) {
      log('No initial SSR data; mounting CSR');

      try {
        rootElement.innerHTML = '';
        const store = createSSRStore<Record<string, unknown>>({});
        render(() => provideSSRStore(store, () => app({ location })), rootElement);
        reportSuccess('CSR mount succeeded');
      } catch (err) {
        reportFailure('CSR mount failed', err);
      }

      return;
    }

    // Hydration path. On the pinned Solid runtime `hydrate(...)` establishes the root synchronously
    // and returns, so a successful return is an honest "root established" signal (design 2). Internal
    // first: the `start` beacon precedes `onStart`, and the `success` beacon precedes `onSuccess`.
    emitBeacons = true;
    reportStart();

    try {
      const store = createSSRStore(initialData);
      hydrate(() => provideSSRStore(store, () => app({ location })), rootElement, renderId ? { renderId } : undefined);
      reportSuccess('Hydration succeeded');
    } catch (err) {
      // A hydration failure reports and STOPS. It deliberately does NOT silently remount as CSR
      // (design 4): a silent remount hides a real server/client divergence behind a page that looks
      // fine, and destroys the server-rendered markup that would have shown the mismatch.
      reportFailure('Hydration failed', err);
    }
  };

  if (document.readyState !== 'loading') bootstrap();
  else document.addEventListener('DOMContentLoaded', bootstrap, { once: true });
}

// packages/react/src/SSRHydration.tsx
import React from 'react';
import { createRoot, hydrateRoot } from 'react-dom/client';

import { createSSRStore, SSRStoreProvider } from './SSRDataStore';
import { createUILogger } from './utils/Logger';

import type { LoggerLike } from './utils/Logger';

// Dev-only introspection hook, set by the server-injected dev script (never by users).
// Absent in production: emission costs one property check and can never throw into
// hydration. User callbacks always run, unchanged, after the internal emission.
type TaujsDevtoolsHook = { emit?: (event: 'hydration:start' | 'hydration:success' | 'hydration:error', payload?: unknown) => void };

const emitDevHook = (event: 'hydration:start' | 'hydration:success' | 'hydration:error', payload?: unknown): void => {
  try {
    const hook = (window as { __TAUJS_DEVTOOLS_HOOK__?: TaujsDevtoolsHook }).__TAUJS_DEVTOOLS_HOOK__;
    hook?.emit?.(event, payload);
  } catch {
    // the beacon must never affect hydration
  }
};

// React 19 root error-info shapes (narrowed from @types/react-dom). Descriptive only.
type RootErrorInfo = { componentStack?: string };

/**
 * Options for {@link hydrateApp}.
 *
 * Lifecycle signals (R2-01):
 * - `onStart` — fires once when hydration BEGINS (hydrate path only; paired with the
 *   `hydration:start` dev beacon, internal-first). NOT fired on the CSR-fallback path.
 * - `onSuccess` — fires once on the FIRST ROOT COMMIT (a component effect, not `hydrateRoot`'s
 *   return). It proves the root committed; it does NOT claim every `<Suspense>` boundary hydrated.
 *   On the hydrate path it is paired with the `hydration:success` beacon (internal-first); on the
 *   CSR-fallback path it fires WITHOUT any beacon (a CSR mount is not a hydration — vue parity).
 * - `onHydrationError` — fires once for a bootstrap failure: an UNCAUGHT client render error
 *   (React's async `onUncaughtError` — a throwing component with no error boundary), a synchronous
 *   setup/invalid-container throw, or a missing root element. On the hydrate path it is paired with
 *   the `hydration:error` beacon; on the CSR path it fires WITHOUT a beacon.
 *
 * Single settlement: EXACTLY ONE of `onSuccess` | `onHydrationError` fires per `hydrateApp` call.
 * Whichever event happens first (first commit vs first uncaught error) wins; any later signal is
 * telemetry — logged only, never re-fired. Errors handled by an app error boundary
 * (`onCaughtError`) and auto-recovered mismatches (`onRecoverableError`, e.g. server/client HTML
 * mismatch) are NOT bootstrap failures — they are logged (`error`/`warn`) and never settle.
 */
export type HydrateAppOptions<T> = {
  appComponent: React.ReactElement;
  rootElementId?: string;
  enableDebug?: boolean;
  logger?: LoggerLike;
  dataKey?: string;
  onHydrationError?: (err: unknown) => void;
  onStart?: () => void;
  onSuccess?: () => void;
};

// Internal reporter (design 2): renders no DOM; its mount effect fires once after the first root
// commit. Mounted INSIDE the provider wrapper, outside user control, so a committed root is provable
// on both the hydrate and CSR paths. StrictMode double-invokes effects in dev — the single-settlement
// flag in the parent makes the repeated `onCommit` a no-op after the first.
const CommitReporter = ({ onCommit }: { onCommit: () => void }): null => {
  React.useEffect(() => {
    onCommit();
  }, [onCommit]);

  return null;
};

export function hydrateApp<T>({
  appComponent,
  rootElementId = 'root',
  enableDebug = false,
  logger,
  dataKey = '__INITIAL_DATA__',
  onHydrationError,
  onStart,
  onSuccess,
}: HydrateAppOptions<T>) {
  const { log, warn, error } = createUILogger(logger, { debugCategory: 'ssr', context: { scope: 'react-hydration' }, enableDebug });

  // User lifecycle callbacks are ADVISORY observers — every one is isolated here. This is not mere
  // defensiveness: `onSuccess` runs INSIDE the reporter's React effect and `onHydrationError` runs
  // inside our root `onUncaughtError` handler. An un-isolated throw from either becomes an exception
  // in React's root-error domain — a throwing `onSuccess` would be routed to our OWN `onUncaughtError`,
  // mis-classified as post-settlement telemetry (success already won), WHILE React tears the committed
  // root down. An observability hook must never destroy the root it observes, escape the adapter, or
  // alter settlement. A throw is logged only. (`emitDevHook` is already self-isolating.)
  const runObserver = (label: string, run: () => void) => {
    try {
      run();
    } catch (cbErr) {
      error(`Hydration ${label} callback threw (ignored):`, cbErr);
    }
  };

  // Beacon policy (path-scoped): the hydrate path emits `hydration:*` beacons; the CSR-fallback path
  // emits NONE (a CSR mount is not a hydration — vue parity). Set once when the path is chosen, and
  // read by the SINGLE report pair below — so one adapter object serves both roots.
  let emitBeacons = false;

  // Single-settlement (design 3): exactly one of success | failure, event-driven (first commit vs
  // first uncaught error). Later signals are runtime telemetry — log-only.
  let settled = false;

  const reportSuccess = () => {
    if (settled) return;
    settled = true;
    if (enableDebug) log('Hydration succeeded (first root commit)');
    if (emitBeacons) emitDevHook('hydration:success');
    runObserver('onSuccess', () => onSuccess?.());
  };

  const reportFailure = (err: unknown) => {
    if (settled) {
      // Post-settlement runtime error: telemetry only (stricter than vue's errored-guard — a
      // deliberate choice recorded in decisions.md as a vue backport candidate).
      error('Post-hydration error (telemetry, not a bootstrap failure):', err);

      return;
    }
    settled = true;
    if (emitBeacons) emitDevHook('hydration:error', err);
    runObserver('onHydrationError', () => onHydrationError?.(err));
  };

  // ONE root-error adapter (design 1), the SAME object passed to whichever root is created
  // (hydrateRoot or createRoot). All client render errors route through the single `reportFailure`.
  const rootErrorOptions = {
    onUncaughtError: (err: unknown, info: RootErrorInfo) => {
      // A render error with no error boundary. React surfaces this ASYNCHRONOUSLY (not as a throw
      // from hydrateRoot/createRoot), so a sync try/catch cannot see it; this is the real client
      // error channel.
      error('Uncaught render error:', err, info);
      // Overriding onUncaughtError REPLACES React's default for the root's ENTIRE lifetime — and its
      // default re-surfaces uncaught errors globally (reportError → a window 'error' event). Without
      // restoring that, post-hydration uncaught render/commit/effect errors (no boundary) would be
      // hidden from window.onerror-based monitoring (Sentry/Bugsnag globalHandlers) — a net
      // observability REGRESSION. Re-surface it (React's own guidance for overriding onUncaughtError)
      // so global observability is preserved ON TOP OF taujs's bootstrap routing below.
      try {
        (globalThis as { reportError?: (e: unknown) => void }).reportError?.(err);
      } catch {
        // global surfacing must never affect hydration
      }
      reportFailure(err);
    },
    onCaughtError: (err: unknown, info: RootErrorInfo) => {
      // Handled by an app error boundary — the app chose how to render it; NOT a bootstrap failure.
      error('Error handled by an app error boundary:', err, info);
    },
    onRecoverableError: (err: unknown, info: RootErrorInfo) => {
      // Auto-recovered (e.g. server/client HTML mismatch → client re-render). A warning, never a
      // failure — do NOT classify a mismatch as a hydration failure.
      warn('Recoverable hydration error:', err, info);
    },
  };

  // The tree React renders, with the internal commit reporter alongside the user's app (renders no
  // DOM, so hydration structure is unaffected). Its effect calls the single `reportSuccess`.
  const buildTree = (store: ReturnType<typeof createSSRStore<T>>) => (
    <React.StrictMode>
      <SSRStoreProvider store={store}>
        {appComponent}
        <CommitReporter onCommit={reportSuccess} />
      </SSRStoreProvider>
    </React.StrictMode>
  );

  const mountCSR = (rootEl: HTMLElement, initialData: T) => {
    // emitBeacons stays false: the CSR path reports onSuccess/onHydrationError but no beacons.
    rootEl.innerHTML = '';
    const store = createSSRStore(initialData);

    try {
      const root = createRoot(rootEl, rootErrorOptions);
      root.render(buildTree(store));
    } catch (err) {
      // Sync belt: invalid container / synchronous setup throw.
      error('CSR mount error:', err);
      reportFailure(err);
    }
  };

  const startHydration = (rootEl: HTMLElement, initialData: T) => {
    emitBeacons = true; // hydrate path: emit hydration:start/success/error beacons

    if (enableDebug) log('Hydration started');
    emitDevHook('hydration:start');
    runObserver('onStart', () => onStart?.());

    if (enableDebug) log('Initial data loaded:', initialData);

    const store = createSSRStore(initialData);
    if (enableDebug) log('Store created:', store);

    try {
      hydrateRoot(rootEl, buildTree(store), rootErrorOptions);
    } catch (err) {
      // Sync belt: invalid container / synchronous setup throw (async render errors arrive via
      // onUncaughtError above, not here).
      error('Hydration error:', err);
      reportFailure(err);
    }
  };

  const bootstrap = () => {
    const rootEl = document.getElementById(rootElementId);
    if (!rootEl) {
      // R5 (design 4): a missing root IS a bootstrap failure. Route it through the same single
      // failure path — the beacon emits an error without a preceding `start` (vue precedent).
      emitBeacons = true;
      error(`Root element with id "${rootElementId}" not found.`);
      reportFailure(new Error(`Root element with id "${rootElementId}" not found.`));

      return;
    }

    const data = (window as any)[dataKey] as T | undefined;

    if (data === undefined) {
      const csrData = {} as T;
      if (enableDebug) warn(`No initial SSR data at window["${dataKey}"]. Mounting CSR.`);
      mountCSR(rootEl, csrData);

      return;
    }

    startHydration(rootEl, data);
  };

  if (document.readyState !== 'loading') {
    bootstrap();
  } else {
    document.addEventListener('DOMContentLoaded', bootstrap, { once: true });
  }
}
