// packages/solid/src/SSRRender.ts
import { renderToStream, renderToStringAsync } from 'solid-js/web';

import { createSSRStore, provideSSRStore } from './SSRDataStore.js';
import { detachStore, getStoreReadiness, getStoreState } from './internal.js';
import { brandRenderFunctions, SOLID_RENDERER_KEY } from './renderContract.js';
import { createUILogger } from './utils/Logger.js';
import { createStreamController, startTimer, wireWritableGuards } from './utils/Streaming.js';

import type { JSX } from 'solid-js';
import type { Writable } from 'node:stream';
import type { SolidLogger } from './utils/Logger.js';

/**
 * The Solid render module (design 2 + 3). Mirrors React's controller SHAPE; its completion, error
 * and cancellation SEMANTICS follow the ruled Solid matrix, which differs in ways that copying
 * React by analogy would erase.
 *
 * What Solid does NOT do, and why it is correct that it does not:
 *
 * `onRenderError` is never invoked, and no `RenderErrorInfo` is ever constructed. The narrow
 * advisory-seam proof (evidence/SEAM-proof-commands.md) FAILED on case 2: what the seroval plugin
 * is handed for a post-shell REJECTED resource and for an ordinary RESOLVED `Error` value is
 * byte-identical, so driving an advisory from it would report render failures on successful
 * responses. Matrix rows #5/#6 are therefore Solid-managed DEGRADED COMPLETION - the stream
 * completes, `done` RESOLVES because transport completed, the serialised rejection is sanitised,
 * and the client `ErrorBoundary` handles it at hydration. A conformance test asserting Solid emits
 * `onRenderError` would be asserting a defect. The callback stays in the contract for React.
 *
 * The one Solid error channel that IS fatal is seroval's SERIALISATION FAILURE (R3) - see
 * `onSerialisationFailure` below. It is a different channel from a successfully serialised
 * rejection and the two are never conflated.
 */

export type HeadContext<T extends Record<string, unknown>, R, H extends Record<string, unknown>> = {
  data: T;
  headData?: H;
  meta: Record<string, unknown>;
  routeContext?: R;
};

export type RenderErrorInfo = {
  error: unknown;
  phase: 'pre-shell' | 'post-shell';
  recoverable: boolean | 'unknown';
};

export type RenderCallbacks<T = unknown> = {
  onHead?: (headContent: string) => void;
  onShellReady?: () => void;
  onAllReady?: (initialData: T) => void;
  onError?: (error: unknown) => void;
  /** Present for contract compatibility. Solid v1 NEVER calls it - see the module note above. */
  onRenderError?: (info: RenderErrorInfo) => void;
};

export type RenderOptions = {
  logger?: SolidLogger;
  routeContext?: unknown;
  headData?: Record<string, unknown>;
  cspNonce?: string;
  shouldHydrate?: boolean;
};

export type InitialDataInput = Record<string, unknown> | Promise<Record<string, unknown>> | (() => Promise<Record<string, unknown>>);

export type RenderStreamHandle = { abort(): void; done: Promise<void> };

export type StreamOptions = {
  /** Bound on shell readiness (default 10_000). */
  shellTimeoutMs?: number;
  /** Bound on the WHOLE renderStream lifecycle (default 30_000). Every terminal clears it. */
  completionTimeoutMs?: number;
};

export type SSROptions = {
  /** Bound on the `ssr` strategy's single render promise (default 10_000). */
  prerenderTimeoutMs?: number;
};

const NOOP = () => {};

/**
 * Normalise the host's `initialData` into the store's `T | Promise<T>` seed.
 *
 * The lazy thunk is invoked EXACTLY ONCE, here, inside the caller's guarded path - and a
 * SYNCHRONOUS throw from it propagates, which the caller turns into a pre-shell fatal (design 1.5).
 */
function normaliseInitialData(initialData: InitialDataInput): Record<string, unknown> | Promise<Record<string, unknown>> {
  return typeof initialData === 'function' ? initialData() : initialData;
}

export function createRenderer<
  T extends Record<string, unknown> = Record<string, unknown>,
  R = unknown,
  H extends Record<string, unknown> = Record<string, unknown>,
>({
  appComponent,
  headContent,
  renderId,
  streamOptions = {},
  ssrOptions = {},
  logger,
}: {
  appComponent: (props: { location: string; routeContext?: R }) => JSX.Element;
  headContent: (ctx: HeadContext<T, R, H>) => string;
  renderId?: string;
  streamOptions?: StreamOptions;
  ssrOptions?: SSROptions;
  logger?: SolidLogger;
}) {
  const { shellTimeoutMs = 10_000, completionTimeoutMs = 30_000 } = streamOptions;
  const { prerenderTimeoutMs = 10_000 } = ssrOptions;

  // Validate ONCE, at the factory. `startTimer` arms only for finite positive values, so without
  // this every invalid input (-1, NaN, null, a string from untyped JS) silently became "no bound"
  // - the watchdog quietly disabled, which is the opposite of what a timeout option means. Only
  // `0` and `Infinity` are documented sentinels for that.
  const assertTimeout = (value: number, name: string): void => {
    const ok = value === 0 || value === Infinity || (typeof value === 'number' && Number.isFinite(value) && value > 0);
    if (!ok) {
      throw new TypeError(`createRenderer: ${name} must be a positive finite number of milliseconds, 0, or Infinity (received ${String(value)})`);
    }
  };
  assertTimeout(shellTimeoutMs, 'streamOptions.shellTimeoutMs');
  assertTimeout(completionTimeoutMs, 'streamOptions.completionTimeoutMs');
  assertTimeout(prerenderTimeoutMs, 'ssrOptions.prerenderTimeoutMs');

  // ---------------------------------------------------------------------------------------------
  // renderSSR - the `ssr` strategy. A SINGLE promise; deliberately no stream vocabulary (INDEX
  // conventions rule 5). The host resolves route data BEFORE calling this.
  // ---------------------------------------------------------------------------------------------
  const renderSSR = async (
    initialDataResolved: Record<string, unknown>,
    location: string,
    meta: Record<string, unknown> = {},
    signal?: AbortSignal,
    opts?: RenderOptions,
  ): Promise<{ headContent: string; appHtml: string }> => {
    const { log, warn } = createUILogger(opts?.logger ?? logger, { debugCategory: 'ssr', context: { scope: 'solid-ssr' } });
    const routeContext = opts?.routeContext as R | undefined;

    if (signal?.aborted) {
      warn('SSR skipped; already aborted');

      return { headContent: '', appHtml: '' };
    }

    // The T/H narrowing seam for this strategy: the contract-facing parameters are BROAD so a
    // renderer instantiated with non-default generics stays assignable to the host contract under
    // strictFunctionTypes; route-config inference is the type authority, as for the body data.
    const store = createSSRStore<Record<string, unknown>>(initialDataResolved);
    const head = headContent({ data: initialDataResolved as T, headData: opts?.headData as H | undefined, meta, routeContext });

    // M1: the SSR single-promise path uses the SAME holder design as streaming. Its timeout is a
    // retention class of its own (S0-B2 R-C), so detachment must happen on every exit - including
    // a mid-render abort, which is the case that previously leaked.
    let settled = false;
    let removeAbortListener = () => {};
    const detach = () => {
      if (settled) return;
      settled = true;
      removeAbortListener();
      detachStore(store);
    };

    try {
      // B1 exp01, pinned by a store test: a SYNCHRONOUS render throw escapes `renderToStringAsync`
      // BEFORE a promise exists. So this must be inside try/catch, not merely `.catch`-ed.
      const rendered = renderToStringAsync(
        () => provideSSRStore(store, () => appComponent({ location, routeContext })),
        // `renderId` scopes Solid's markers/data. Hydration/CSP policy (the design 4 truth table,
        // incl. `nonce` and `noScripts`) is slice 4 and is deliberately NOT implemented here.
        { renderId } as never,
      ) as Promise<string>;

      // Solid exposes no way to cancel an in-flight render, so an abandoned one runs to completion
      // (or never settles). Pre-observe it: without this, a render that eventually REJECTS after we
      // have already returned raises an `unhandledRejection` - a process exit under Node's default
      // mode. Detachment is what bounds the abandoned render's cost: the root may outlive the
      // response, but it holds no τjs state.
      rendered.catch(() => {});

      const timeoutError = new Error(`Solid SSR render exceeded prerenderTimeoutMs (${prerenderTimeoutMs}ms)`);
      let stopTimer = () => {};
      const deadline = new Promise<never>((_, reject) => {
        stopTimer = startTimer(prerenderTimeoutMs, () => reject(timeoutError));
      });

      // Race the caller's signal too. Checking `signal.aborted` only before and after the render
      // left an abort DURING a never-settling render waiting for the prerender deadline, holding
      // the request and the holder for up to `prerenderTimeoutMs`.
      const ABORTED = Symbol('aborted');
      const abortRace = new Promise<typeof ABORTED>((resolve) => {
        if (!signal) return;
        const onAbort = () => resolve(ABORTED);
        signal.addEventListener('abort', onAbort, { once: true });
        removeAbortListener = () => {
          try {
            signal.removeEventListener('abort', onAbort);
          } catch {}
        };
      });

      let outcome: string | typeof ABORTED;
      try {
        outcome = await Promise.race([rendered, deadline, abortRace]);
      } finally {
        stopTimer();
      }

      if (outcome === ABORTED || signal?.aborted) {
        warn('SSR aborted by caller');

        // `detach()` runs in the `finally` below - promptly, not at the prerender deadline.
        return { headContent: '', appHtml: '' };
      }

      log('Completed SSR');

      return { headContent: head, appHtml: outcome };
    } finally {
      detach();
    }
  };

  // ---------------------------------------------------------------------------------------------
  // renderStream - the `streaming` strategy.
  // ---------------------------------------------------------------------------------------------
  const renderStream = (
    sink: Writable,
    callbacks: RenderCallbacks<T> = {},
    initialData: InitialDataInput,
    location: string,
    bootstrapModules?: string,
    meta: Record<string, unknown> = {},
    signal?: AbortSignal,
    opts?: RenderOptions,
  ): RenderStreamHandle => {
    const cb = {
      onHead: callbacks.onHead ?? NOOP,
      onShellReady: callbacks.onShellReady ?? NOOP,
      onAllReady: (callbacks.onAllReady ?? NOOP) as (data: T) => void,
      onError: callbacks.onError ?? NOOP,
    };
    const { log, warn, error } = createUILogger(opts?.logger ?? logger, { debugCategory: 'ssr', context: { scope: 'solid-streaming' } });
    const routeContext = opts?.routeContext as R | undefined;

    const controller = createStreamController(sink, { log, warn, error });

    /**
     * The single fatal site. Claims the terminal FIRST, then runs the host's isolated `onError`:
     * the host callback may synchronously abort the very AbortSignal wired to `benignAbort`, and a
     * re-entrant benign abort arriving first would win the one-shot controller and RESOLVE `done`,
     * silently downgrading a fatal and violating the handle contract.
     */
    const failFatal = (err: unknown) => {
      if (controller.terminated) return;
      controller.fatalAbort(err);
      try {
        cb.onError(err);
      } catch (cbErr) {
        warn('onError callback threw', cbErr);
      }
    };

    // Completion watchdog: bounds the WHOLE lifecycle, including the exactly-once lazy thunk and
    // post-shell no-end. Every terminal clears it (registered as controller cleanup).
    const stopCompletionTimer = startTimer(completionTimeoutMs, () => {
      if (controller.terminated) return;
      failFatal(
        new Error(
          controller.shellCommitted
            ? `Solid stream did not complete within completionTimeoutMs (${completionTimeoutMs}ms); shell was committed, so the document is incomplete`
            : `Solid stream did not reach shell within completionTimeoutMs (${completionTimeoutMs}ms)`,
        ),
      );
    });
    controller.addCleanup(stopCompletionTimer);

    // The shell timer is NOT armed here. The ruled contract (design 2) starts it "immediately
    // before the Solid render begins", and the completion timer bounds the WHOLE lifecycle
    // INCLUDING route-data resolution. Arming it here would charge a slow loader against the shell
    // budget and report a data stall as a shell stall - two different faults with two different
    // operator responses. It is armed in `runRender` instead.
    let stopShellTimer = () => {};
    controller.addCleanup(() => stopShellTimer());

    const { cleanup: guardsCleanup } = wireWritableGuards(sink, {
      benignAbort: (why) => controller.benignAbort(why),
      fatalAbort: (err) => failFatal(err),
    });
    controller.addCleanup(guardsCleanup);

    if (signal) {
      const onAbort = () => controller.benignAbort('AbortSignal triggered; cancelling Solid stream');
      if (signal.aborted) {
        controller.benignAbort('AbortSignal already aborted before render');

        return { abort: NOOP, done: controller.done };
      }
      signal.addEventListener('abort', onAbort, { once: true });
      controller.addCleanup(() => {
        try {
          signal.removeEventListener('abort', onAbort);
        } catch {}
      });
    }

    // --- store construction. The lazy thunk runs EXACTLY ONCE, here, and a synchronous throw is a
    // pre-shell fatal (design 1.5).
    let store: ReturnType<typeof createSSRStore<Record<string, unknown>>>;
    try {
      store = createSSRStore<Record<string, unknown>>(normaliseInitialData(initialData));
    } catch (thunkThrow) {
      failFatal(thunkThrow);

      return { abort: NOOP, done: controller.done };
    }
    // M1: every terminal releases τjs-owned request state, exactly once (the controller enforces
    // the once-ness across all terminal kinds).
    controller.setDetach(() => detachStore(store));

    const readiness = getStoreReadiness(store) ?? Promise.resolve();

    // --- two-latch `onAllReady` (design 2, binding: ESC-0 C3 CONFIRMED). Route-data-ready AND
    // Solid-completed, then exactly once. A fatal incomplete delivery calls NEITHER latch, so it
    // never seeds a truncated document.
    let dataReady = false;
    let solidCompleted = false;
    let allReadyFired = false;

    const tryFireAllReady = () => {
      if (allReadyFired || controller.terminated) return;
      if (!dataReady || !solidCompleted) return;

      const state = getStoreState(store);
      // A rejected route load is a PRE-shell fatal owned by the gate below; it must never seed.
      if (state?.status !== 'success') return;

      allReadyFired = true;
      try {
        cb.onAllReady(store.data() as T);
      } catch (cbErr) {
        // Matrix row #9: advisory-callback throws are ISOLATED; the response still completes.
        error('onAllReady callback threw', cbErr);
      }
    };

    void readiness.then(() => {
      dataReady = true;
      tryFireAllReady();
    });

    // --- the delegating sink. Solid calls write/end on this; the terminal guard makes both
    // no-ops after a terminal so a late Solid settlement resumes nothing (RFC 0006:330).
    let endRequested = false;
    const facade = {
      write: (chunk: unknown): boolean => {
        if (controller.terminated) return true;

        try {
          return sink.write(chunk as Uint8Array);
        } catch (writeErr) {
          // A SYNCHRONOUS write failure is render-origin by construction (Solid is mid-render and
          // called us). Matrix #7a: never benign by shape. Without this it escapes into Solid's
          // internals, where there is no handler - the response then hangs until a watchdog fires
          // instead of failing immediately.
          failFatal(writeErr);

          return true;
        }
      },
      end: () => {
        if (controller.terminated || endRequested) return;
        endRequested = true;

        // Solid has finished. Defer the real `end()` until route data has settled so the host's
        // finish listener serialises the authoritative value rather than `{}`.
        void readiness.then(() => {
          if (controller.terminated) return;

          const state = getStoreState(store);
          if (state?.status !== 'success') {
            failFatal(state?.error ?? new Error('Solid stream: route data unavailable at completion'));

            return;
          }

          try {
            if (!sink.writableEnded && !sink.destroyed) sink.end();
          } catch (endErr) {
            failFatal(endErr);

            return;
          }
          controller.complete('Solid stream completed');
        });
      },
      destroy: (err?: unknown) => {
        // Terminal-guarded like every other adapter-owned sink op: after a terminal the controller
        // already owns the sink's fate, and a late Solid-initiated destroy must resume nothing.
        if (controller.terminated) return facade;
        try {
          sink.destroy(err as Error | undefined);
        } catch {}

        return facade;
      },
      on: (event: string, handler: (...args: unknown[]) => void) => (sink.on(event, handler), facade),
      once: (event: string, handler: (...args: unknown[]) => void) => (sink.once(event, handler), facade),
      removeListener: (event: string, handler: (...args: unknown[]) => void) => (sink.removeListener(event, handler), facade),
      emit: (event: string, ...args: unknown[]) => sink.emit(event, ...args),
      get destroyed() {
        return sink.destroyed;
      },
      get writable() {
        return sink.writable;
      },
    };

    const runRender = () => {
      const state = getStoreState(store);
      if (state?.status !== 'success') {
        // Snapshot bridge: route-data rejection is a PRE-SHELL FATAL, never a post-shell `{}` seed
        // (design 3; C2 correction).
        failFatal(state?.error ?? new Error('Solid stream: route data failed before render'));

        return;
      }

      // The head is COMPUTED here (route data is committed by now), but deliberately NOT emitted
      // here. In the real host `onHead` writes the 200 response head and connects the stream, so
      // calling it before the render would commit a 200 for a response that may still fail
      // pre-shell - a synchronous root throw, or an R3 serialisation failure that fires before
      // `onCompleteShell`, would both arrive with the response already committed. It is invoked
      // from `onCompleteShell` below, immediately BEFORE the shell is marked committed.
      let head: string;
      try {
        head = headContent({ data: store.data() as T, headData: opts?.headData as H | undefined, meta, routeContext });
      } catch (headErr) {
        failFatal(headErr);

        return;
      }

      // Design 2: "the shell timer starts immediately before the Solid render begins".
      stopShellTimer = startTimer(shellTimeoutMs, () => {
        if (controller.terminated || controller.shellCommitted) return;
        failFatal(new Error(`Solid shell not ready after ${shellTimeoutMs}ms`));
      });

      let stream: { pipe: (destination: unknown) => void };
      try {
        // `renderToStream(...).pipe(w)` DIRECTLY - never `pipeToNodeWritable`/`pipeToWritable`
        // with `onReady`, which OVERWRITE a caller-supplied `onCompleteShell`
        // (solid-js/web/dist/server.js:693,709) and would silently break the shell latch below.
        stream = renderToStream(() => provideSSRStore(store, () => appComponent({ location, routeContext })), {
          renderId,
          onCompleteShell() {
            if (controller.terminated) return;
            stopShellTimer();

            // onHead is operationally REQUIRED: it commits the response head and connects the
            // sink. A throwing onHead is FATAL (matrix row #8) and must leave the shell UNMARKED,
            // so the fatal teardown still treats this as pre-shell and never claims a committed
            // document.
            try {
              cb.onHead(head);
            } catch (headErr) {
              failFatal(headErr);

              return;
            }

            controller.markShellCommitted();

            try {
              cb.onShellReady();
            } catch (cbErr) {
              // Matrix row #9: isolated. Solid itself does NOT isolate these (B1 exp09b), so the
              // adapter must, or a throw here becomes an unhandledRejection and the stream hangs.
              error('onShellReady callback threw', cbErr);
            }
          },
          onCompleteAll() {
            if (controller.terminated) return;
            solidCompleted = true;
            tryFireAllReady();
          },
          /**
           * R3: seroval's SERIALISATION FAILURE channel. This is NOT a successfully serialised
           * resource rejection (#5/#6, which is unobservable degraded completion) - it means the
           * payload cannot be completed safely, so it is FATAL infrastructure/delivery failure.
           * Pre-shell: never commit. Post-shell: destroy the sink, never `end()`, never claim
           * completed delivery. The controller enforces both and settles exactly once.
           */
          onError(serialisationError: unknown) {
            if (controller.terminated) return;
            failFatal(serialisationError);
          },
        } as never) as never;
      } catch (renderThrow) {
        // Matrix row #1: a synchronous root throw precedes any handle.
        failFatal(renderThrow);

        return;
      }

      stream.pipe(facade);
    };

    // Snapshot bridge: the adapter must hold the RESOLVED route value before rendering, so the
    // whole render is gated on readiness. The documented consequence is that a route-data stall
    // blocks shell emission entirely - bounded by the shell and completion watchdogs above.
    void readiness.then(() => {
      if (controller.terminated) return;
      try {
        runRender();
      } catch (outer) {
        failFatal(outer);
      }
    });

    void bootstrapModules; // slice 4 (hydration/CSP) owns bootstrap emission.

    return {
      abort: () => controller.benignAbort('Manual abort'),
      done: controller.done,
    };
  };

  // Renderer v1: the identity brand goes on BOTH functions (function-level, so it survives the
  // scaffold's `export const { renderSSR, renderStream } = createRenderer(...)` destructure).
  return brandRenderFunctions({ renderSSR, renderStream }, SOLID_RENDERER_KEY);
}

// packages/react/src/SSRRender.tsx
import React from 'react';
import { renderToPipeableStream, renderToString } from 'react-dom/server';

import type { Writable } from 'node:stream';

import { createSSRStore, SSRStoreProvider } from './SSRDataStore';
import { getStoreReadiness } from './internal';
import { createUILogger } from './utils/Logger';

import type { LoggerLike } from './utils/Logger';

import { createStreamController, startShellTimer, wireWritableGuards } from './utils/Streaming';

/**
 * R1-01: structured, NON-FATAL render-error observation.
 *
 * `phase` is the OBSERVED timing — had the shell committed when React's `onError` fired? It is
 * descriptive only and NEVER a fatality signal (a `pre-shell` `onError` can be followed by a
 * successful shell commit, verified against real react-dom/server). `recoverable` is `true` only
 * for `post-shell` errors (boundary-scoped — React recovers them client-side) and `'unknown'` for
 * `pre-shell` (its outcome is resolved by the separate fatal channels: a subsequent `onShellError`
 * fails the render, a subsequent shell commit means it recovered).
 */
export type RenderErrorInfo = {
  error: unknown;
  phase: 'pre-shell' | 'post-shell';
  recoverable: boolean | 'unknown';
};

export type RenderCallbacks<T> = {
  /**
   * REQUIRED (operationally): commits the response head + connects the sink. A throwing `onHead`
   * enters the fatal path — the response cannot proceed without it.
   */
  onHead?: (head: string) => void;
  /** Advisory (observes; isolated — a throw is logged, not fatal). */
  onShellReady?: () => void;
  /** Advisory. Fires exactly once with the resolved route data. */
  onAllReady?: (data: T) => void;
  /** @deprecated Legacy alias of `onAllReady`, fires when final data is available. Use `onAllReady`. */
  onFinish?: (data: T) => void;
  /** FATAL error channel: a fatal stream error (shell error / timeout / guard / non-recoverable). */
  onError?: (err: unknown) => void;
  /**
   * Advisory, NON-FATAL structured render-error channel (R1-01). Fires for React render errors that
   * do NOT themselves fail the response — notably post-shell boundary errors React recovers
   * client-side. Never a fatality signal; fatality stays with `onError`/`onShellError`/timers/guards.
   */
  onRenderError?: (info: RenderErrorInfo) => void;
};

export type StreamOptions = {
  /** Timeout in ms for shell to be ready (default: 10000) */
  shellTimeoutMs?: number;
  /**
   * R1-01: timeout in ms for route data to settle AFTER React has finished rendering, before the
   * response is failed (default: 30000). Bounds the end-gate so a never-settling loader cannot hold
   * the response (and its listeners/streams) open indefinitely.
   */
  dataTimeoutMs?: number;
};

/**
 * Context passed to `headContent`: `data` is the resolved route data, `meta`/`routeContext` the
 * route's static metadata and per-request context. NB `headContent` returns RAW `<head>` HTML — any
 * value interpolated from `data` (or other services/user input) must be escaped with `escapeHtml`
 * (see the `headContent` option's docs).
 */
export type HeadContext<T extends Record<string, unknown> = Record<string, unknown>, R = unknown> = {
  data: T;
  meta: Record<string, unknown>;
  routeContext?: R;
};

type SSRResult = { headContent: string; appHtml: string; aborted: boolean };

type StreamCallOptions<R> = StreamOptions & {
  logger?: LoggerLike;
  routeContext?: R;
};

const NOOP = () => {};

export function createRenderer<T extends Record<string, unknown> = Record<string, unknown>, R = unknown>({
  appComponent,
  headContent,
  streamOptions = {},
  logger,
  enableDebug = false,
  identifierPrefix,
}: {
  appComponent: (props: { location: string; routeContext?: R }) => React.ReactElement;
  /**
   * Returns the per-route `<head>` inner HTML. The return value is written into `<head>` VERBATIM as
   * RAW HTML — it is deliberately NOT auto-escaped, so you can emit `<meta>`/`<link>`/`<script>` tags.
   * Therefore any value interpolated from `data` (services or user input) MUST be escaped first with
   * `escapeHtml` (exported from `@taujs/react`), e.g.
   * `` `<meta property="og:image" content="${escapeHtml(data.ogImage)}">` ``. See the head-management
   * guide, "Best Practices — Escape User Content".
   */
  headContent: (ctx: HeadContext<T, R>) => string;
  enableDebug?: boolean;
  logger?: LoggerLike;
  streamOptions?: StreamOptions;
  /**
   * React's `identifierPrefix` for `useId` (passed to `renderToString` and `renderToPipeableStream`).
   * It MUST be identical on the server and the client for a given root (pass the same value to
   * `hydrateApp`), or hydration mismatches. Set it when rendering MORE THAN ONE τjs root on a page
   * (the app-per-boundary / micro-frontend model) so each root's `useId` values are collision-free.
   * A server-derived default from `appId` is a possible future (R3-03); today it is app-supplied.
   */
  identifierPrefix?: string;
}) {
  const { shellTimeoutMs = 10_000, dataTimeoutMs = 30_000 } = streamOptions;

  const renderSSR = async (
    initialData: T,
    location: string,
    meta: Record<string, unknown> = {},
    signal?: AbortSignal,
    opts?: { logger?: LoggerLike; routeContext?: R },
  ): Promise<SSRResult> => {
    const { log, warn } = createUILogger(opts?.logger ?? logger, {
      debugCategory: 'ssr',
      context: { scope: 'react-ssr' },
      enableDebug,
    });

    if (signal?.aborted) {
      warn('SSR skipped; already aborted', { location });

      return { headContent: '', appHtml: '', aborted: true };
    }

    let aborted = false;
    const onAbort = () => (aborted = true);
    signal?.addEventListener('abort', onAbort, { once: true });

    const routeContext = opts?.routeContext;

    try {
      log('Starting SSR:', location);

      const dynamicHead = headContent({ data: initialData, meta, routeContext });
      const store = createSSRStore(initialData);
      const html = renderToString(<SSRStoreProvider store={store}>{appComponent({ location, routeContext })}</SSRStoreProvider>, {
        identifierPrefix,
      });

      if (aborted) {
        warn('SSR completed after client abort', { location });

        return { headContent: '', appHtml: '', aborted: true };
      }

      log('Completed SSR:', location);

      return { headContent: dynamicHead, appHtml: html, aborted: false };
    } finally {
      try {
        signal?.removeEventListener('abort', onAbort);
      } catch {}
    }
  };

  const renderStream = (
    writable: Writable,
    callbacks: RenderCallbacks<T> = {},
    initialData: T | Promise<T> | (() => Promise<T>),
    location: string,
    bootstrapModules?: string,
    meta: Record<string, unknown> = {},
    cspNonce?: string,
    signal?: AbortSignal,
    opts?: StreamCallOptions<R>, // per-call override
  ) => {
    const cb = {
      onHead: callbacks.onHead ?? NOOP,
      onShellReady: callbacks.onShellReady ?? NOOP,
      onAllReady: callbacks.onAllReady ?? NOOP,
      onFinish: callbacks.onFinish ?? NOOP,
      onError: callbacks.onError ?? NOOP,
      onRenderError: callbacks.onRenderError ?? (NOOP as (info: RenderErrorInfo) => void),
    };
    const { log, warn, error } = createUILogger(opts?.logger ?? logger, {
      debugCategory: 'ssr',
      context: { scope: 'react-streaming' },
      enableDebug,
    });
    const routeContext = opts?.routeContext;

    // Merge renderer defaults with per-call overrides
    const effectiveShellTimeout = opts?.shellTimeoutMs ?? shellTimeoutMs;
    const effectiveDataTimeout = opts?.dataTimeoutMs ?? dataTimeoutMs;

    // Stream controller centralises cleanup & settlement
    const controller = createStreamController(writable, { log, warn, error });

    // EVERY fatal path routes through here (single site that fires `cb.onError` for a fatal —
    // no double-fire). The ORIGINAL error is the rejection reason.
    //
    // Ordering (gate-review finding 2): claim the terminal fatal state via `controller.fatalAbort`
    // FIRST, THEN run the isolated host `cb.onError`. The host callback may SYNCHRONOUSLY abort the
    // very AbortSignal we wired to `controller.benignAbort` (the server's `onError` calls
    // `ac.abort()`, and `ac.signal` is this renderer's `signal`). If that re-entrant benign abort
    // ran BEFORE we claimed fatal, it would win the one-shot controller and RESOLVE `done` — silently
    // downgrading a fatal to a benign completion and violating the `RenderStreamHandle` contract
    // (fatal ⇒ `done` rejects). fatalAbort-first makes the re-entrant `benignAbort` a no-op.
    //
    // `cb.onError` is still SWALLOWED on throw (and cannot veto settlement, already claimed) — it may
    // run from a timer or a writable EventEmitter listener where a throw would be an uncaughtException.
    const failFatal = (err: unknown) => {
      controller.fatalAbort(err);
      try {
        cb.onError(err);
      } catch (cbErr) {
        warn('onError callback threw:', cbErr);
      }
    };

    // Wire AbortSignal (benign cancel)
    if (signal) {
      const handleAbortSignal = () => controller.benignAbort(`AbortSignal triggered; aborting stream for location: ${location}`);

      if (signal.aborted) {
        handleAbortSignal();

        return { abort: () => {}, done: Promise.resolve() };
      }

      signal.addEventListener('abort', handleAbortSignal, { once: true });
      controller.setRemoveAbortListener(() => {
        try {
          signal.removeEventListener('abort', handleAbortSignal);
        } catch {}
      });
    }

    // Set by armDataDeadline (below) to its idempotent disarm. Composed into the controller's cleanup
    // so ANY termination path tears the data deadline down PROMPTLY — the recheck showed relying on the
    // writable's 'close' event is unsound (a writable created with `emitClose: false` is destroyed
    // without emitting 'close', leaving the timer/closure/listener live until dataTimeoutMs).
    let stopDataDeadline: (() => void) | undefined;

    // Writable guards (handles error/close/finish)
    const { cleanup: guardsCleanup } = wireWritableGuards(writable, {
      benignAbort: (why) => controller.benignAbort(why),
      fatalAbort: (err) => failFatal(err),
      onFinish: () => controller.complete('Stream finished (normal completion)'),
    });
    controller.setGuardsCleanup(() => {
      try {
        guardsCleanup();
      } catch {}
      try {
        stopDataDeadline?.();
      } catch {}
    });

    // Shell timeout guard
    const stopShellTimer = startShellTimer(effectiveShellTimeout, () => {
      if (controller.isAborted) return;

      const timeoutErr = new Error(`Shell not ready after ${effectiveShellTimeout}ms`);
      failFatal(timeoutErr);
    });
    controller.setStopShellTimer(stopShellTimer);

    log('Starting stream:', location);

    let piped = false;
    let shellCommitted = false;
    let delivered = false;

    try {
      // Store is created here so the renderer can read its INTERNAL readiness (design 1) for the
      // bounded end-gate; the public SSRStore type is unchanged.
      const store = createSSRStore(initialData);
      const readiness = getStoreReadiness(store) ?? Promise.resolve();

      // Single-fire delivery (design 2): fires onAllReady/onFinish exactly once, from the end-gate
      // after data has settled — replacing the thrown-thenable retry dance. Reading the snapshot can
      // still throw (e.g. a loader that resolves to `undefined` settles status:'success' with no
      // data): route that through failFatal so it becomes a clean fatal, never a hung response.
      const deliverFinalData = () => {
        if (delivered) return;

        let data: T;
        try {
          data = store.getSnapshot();
        } catch (snapErr) {
          failFatal(snapErr instanceof Error ? snapErr : new Error('SSR data unavailable at delivery'));
          return;
        }

        delivered = true;
        try {
          cb.onAllReady(data);
        } catch (cbErr) {
          error('onAllReady callback threw:', cbErr);
        }
        try {
          cb.onFinish(data);
        } catch (cbErr) {
          error('onFinish callback threw:', cbErr);
        }
      };

      // Route-data liveness deadline (design 3, gate-review finding 1). The bound on route-data
      // settlement must NOT depend on React calling the sink's end(): a <Suspense> consumer of the
      // store keeps React's stream open until the thrown data promise settles, so for a never-settling
      // loader React NEVER ends — and if the deadline lived only in the end path (below) nothing would
      // ever fire. Arm it explicitly once the shell is committed (a post-shell data budget matching
      // `dataTimeoutMs`), independent of end(). On expiry it enters the single fatal path (which aborts
      // React + tears the response down).
      //
      // Teardown (recheck finding): it is disarmed when route data settles, on controller termination
      // (via `stopDataDeadline`, composed into the controller cleanup above — the AUTHORITATIVE path,
      // since a writable with `emitClose: false` never emits 'close'), and defensively on 'close'.
      // `teardown` ALWAYS clears the timer and removes the listener idempotently, including after the
      // timer itself has won — so nothing (timer, closure, listener, readiness continuation) is
      // retained past the terminal event.
      let dataDeadlineArmed = false;
      const armDataDeadline = () => {
        if (dataDeadlineArmed) return;
        dataDeadlineArmed = true;
        if (store.status !== 'pending') return; // already settled — nothing to bound

        let timer: ReturnType<typeof setTimeout>;
        const teardown = () => {
          clearTimeout(timer);
          try {
            writable.removeListener('close', disarm);
          } catch {}
        };
        let settled = false;
        const disarm = () => {
          if (settled) return;
          settled = true;
          teardown();
        };
        timer = setTimeout(() => {
          if (settled) return;
          settled = true;
          teardown(); // clear our own listener even when the timer wins
          if (controller.isAborted) return; // another path already owns settlement
          failFatal(new Error(`Route data not ready after ${effectiveDataTimeout}ms`));
        }, effectiveDataTimeout);

        // Data settled (resolve OR swallowed error) → disarm. Controller termination → stopDataDeadline
        // (authoritative). 'close' is a secondary signal for the emitClose:true case.
        readiness.then(disarm, disarm);
        writable.once('close', disarm);
        stopDataDeadline = disarm;
      };

      // Deferred end (design 2/3): React pipes final output into the delegating sink; we defer the
      // real writable's end() until route data has settled so LATE data (no-consumer path) is
      // serialized before finish. Liveness is owned by armDataDeadline above, NOT here — so a Suspense
      // consumer whose data never settles (React never reaches this end()) is still bounded.
      let endStarted = false;
      const deferredEnd = () => {
        if (controller.isAborted || endStarted) return;
        endStarted = true;

        readiness
          .then(() => {
            // Aborted during the data wait (incl. the data deadline firing): the writable is already
            // torn down — do not deliver to a gone response nor end() a destroyed stream.
            if (controller.isAborted) return;
            if (store.status === 'error') {
              failFatal(store.lastError ?? new Error('SSR data fetch failed'));
              return;
            }
            deliverFinalData();
            // deliverFinalData may itself fatal-abort (e.g. undefined snapshot); don't end() then.
            if (controller.isAborted) return;
            writable.end();
          })
          .catch((e) => {
            if (controller.isAborted) return;
            failFatal(e);
          });
      };

      // React only ever calls write(view) [single chunk arg], end(), destroy(err), on/once/
      // removeListener(event, handler), and (guarded) flush(). We omit flush() so React skips it,
      // and forward the rest to the real writable so its own listeners/backpressure are authoritative.
      const endGate = {
        write: (chunk: unknown): boolean => (controller.isAborted ? true : writable.write(chunk as Uint8Array)),
        end: () => deferredEnd(),
        destroy: (err?: unknown) => writable.destroy(err as Error | undefined),
        on: (event: string, handler: (...args: unknown[]) => void) => (writable.on(event, handler), endGate),
        once: (event: string, handler: (...args: unknown[]) => void) => (writable.once(event, handler), endGate),
        removeListener: (event: string, handler: (...args: unknown[]) => void) => (writable.removeListener(event, handler), endGate),
        emit: (event: string, ...args: unknown[]) => writable.emit(event, ...args),
        get destroyed() {
          return writable.destroyed;
        },
        get writable() {
          return writable.writable;
        },
      };

      const appElement = <SSRStoreProvider store={store}>{appComponent({ location, routeContext })}</SSRStoreProvider>;

      const stream = renderToPipeableStream(appElement, {
        nonce: cspNonce,
        identifierPrefix,
        bootstrapModules: bootstrapModules ? [bootstrapModules] : undefined,

        onShellReady() {
          if (controller.isAborted) return;

          try {
            stopShellTimer();
          } catch {}

          log('Shell ready:', location);

          try {
            // Prefer current snapshot if available (sync path).
            let headData: T | undefined;
            try {
              headData = store.getSnapshot();
            } catch (thrown) {
              // In async/lazy cases, snapshot may not be ready yet. That's fine.
              // If it's a promise (thenable), attach a rejection handler to prevent unhandled rejection
              if (thrown && typeof (thrown as any).then === 'function') {
                (thrown as Promise<unknown>).catch(() => {
                  // swallowed; will be handled in onAllReady
                });
              }
            }

            const head = headContent({ data: headData ?? ({} as T), meta, routeContext });

            // onHead is REQUIRED (design 6): it commits the response head and connects the sink. A
            // throwing onHead is fatal — do NOT pipe into an unconsumed sink (hung response).
            try {
              cb.onHead(head);
            } catch (cbErr) {
              failFatal(cbErr);
              return;
            }

            if (!piped) {
              piped = true;
              shellCommitted = true;
              // The delegating sink duck-types the Node Writable surface React's pipe uses.
              stream.pipe(endGate as unknown as Writable);
            }

            // Shell is committed: bound the remaining route-data wait independent of React's end()
            // (finding 1) — a Suspense consumer whose data never settles keeps React streaming, so
            // React may never call end(); this deadline fires regardless.
            armDataDeadline();

            // Advisory (design 6): a throw is logged, not fatal.
            try {
              cb.onShellReady();
            } catch (cbErr) {
              error('onShellReady callback threw:', cbErr);
            }
          } catch (err) {
            failFatal(err);
          }
        },
        onAllReady() {
          // Delivery is owned by the bounded end-gate (deferred until data readiness). This is
          // advisory — React signalling all content is ready.
          if (controller.isAborted) return;
          log('All content ready:', location);
        },

        onShellError(err) {
          if (controller.isAborted) return;

          try {
            stopShellTimer();
          } catch {}

          failFatal(err);
        },

        onError(err) {
          if (controller.isAborted) return;

          // R3 + recoverability ruling (decisions 2026-07-11): React's onError fires for EVERY
          // render error, INCLUDING post-shell boundary errors it recovers client-side. `phase` is
          // the OBSERVED timing (had the shell committed when onError fired) — descriptive only,
          // NEVER a fatality signal. `recoverable` is true only post-shell (boundary-scoped by
          // React's semantics), 'unknown' pre-shell (its outcome is resolved by the separate fatal
          // channels: a subsequent onShellError fails it; a subsequent shell commit means it
          // recovered). This channel is NON-FATAL — fatality stays with onShellError / timers /
          // guards / outer catch.
          const phase: RenderErrorInfo['phase'] = shellCommitted ? 'post-shell' : 'pre-shell';
          const recoverable: RenderErrorInfo['recoverable'] = phase === 'post-shell' ? true : 'unknown';

          // Recheck-2: pass the RAW error to the non-throwing UI logger (no eager coercion).
          error('React render error:', err);

          // Advisory (design 6): isolate a throwing onRenderError.
          try {
            cb.onRenderError({ error: err, phase, recoverable });
          } catch (cbErr) {
            error('onRenderError callback threw:', cbErr);
          }
        },
      });

      controller.setStreamAbort(() => stream.abort());
    } catch (err) {
      failFatal(err);
    }

    return {
      abort: () => controller.benignAbort(`Manual abort for location: ${location}`),
      done: controller.done, // resolves on success/benign cancel; rejects on fatal error
    };
  };

  return { renderSSR, renderStream };
}
