// packages/react/src/SSRDeferredData.tsx
import React, { createContext, use, useContext } from 'react';

/**
 * RFC 0007 - the @taujs/react deferred-data adapter: the smallest projection of a named host
 * promise into React's own `use()` + `<Suspense>` model.
 *
 *  - SERVER: `opts.deferredData` (the host's request-local registry) becomes one tracked thenable
 *    per CONSUMED key. Reading suspends only the reading boundary, and React's OWN streaming and
 *    patch mechanism delivers the late HTML - τjs emits no framework-patch bytes.
 *  - CLIENT: each consumed boundary is seeded from the private end-of-stream envelope, read
 *    synchronously in document order by the bootstrap, so hydration re-executes no loader and
 *    issues no refetch. Every seeded entry is ALREADY SETTLED, so `use()` returns (or throws)
 *    synchronously - no suspension, no second render pass.
 *
 * Host contract this adapter consumes and never re-implements: entries are already started and
 * already pre-observed; a resolved entry is the host's settlement snapshot (parsed JSON, sharing no
 * identity with the loader's object); a value that could not be snapshotted arrives as a
 * detail-free rejection, indistinguishable from any other rejected entry.
 *
 * EXPORT HYGIENE (renderer contract item 9 / decision 10): only `createDeferredAccessor`,
 * `useDeferredData`, `useDeferredDataResult`, `DeferredDataError` and the `DeferredResult` type
 * reach `index.ts`. The carrier constant, both holders, the provider and the hydration reader are
 * private transport - module-exported for `SSRRender`/`SSRHydration` and the package's own tests,
 * never from the package root.
 */

/** @internal The host's internal transport (`RenderOptions.deferredData`), structurally re-stated. */
export type DeferredDataRegistry = Readonly<Record<string, Promise<Record<string, unknown>>>>;

/** @internal RFC 0007 (R4): the only three v1 outcomes. `failed` carries NO message, stack or detail. */
export type DeferredOutcome = { status: 'complete'; value: Record<string, unknown> } | { status: 'failed' } | { status: 'aborted' };

/** @internal */
export type DeferredHydrationState = Readonly<Record<string, DeferredOutcome>>;

/**
 * @internal The private, UNDOCUMENTED envelope carrier the host attaches at its existing
 * end-of-stream write site. Applications must never read it: it is not exported from the package
 * root, and the bootstrap reads it once and deletes it.
 */
export const DEFERRED_STATE_CARRIER = '__TAUJS_DEFERRED_STATE__';

/**
 * The terminal error for a boundary whose value never arrived, thrown by the THROWING accessor.
 *
 * Both non-complete outcomes reject, and the two are distinguishable by `outcome` so an application
 * can render "unavailable" differently from "failed" without ever seeing server detail. Nothing
 * here carries a server message, stack or cause - `key` is route CONFIGURATION, already visible in
 * the application's own source.
 */
export class DeferredDataError extends Error {
  readonly key: string;
  readonly outcome: 'failed' | 'aborted';

  constructor(key: string, outcome: 'failed' | 'aborted') {
    super(`taujs: deferred data "${key}" did not arrive (${outcome})`);
    this.name = 'DeferredDataError';
    this.key = key;
    this.outcome = outcome;
  }
}

/** The typed, per-key result an application branches on - structurally the envelope's own shape. */
export type DeferredResult<T extends Record<string, unknown> = Record<string, unknown>> =
  { status: 'complete'; value: T } | { status: 'failed' } | { status: 'aborted' };

/**
 * React's `use()` thenable protocol: a thenable carrying `status`/`value`/`reason` is consumed
 * SYNCHRONOUSLY when already settled, and suspends only while `status === 'pending'`. This is the
 * shape React itself produces for cached/streamed promises, and it is what makes a hydration read
 * of an already-complete outcome a zero-suspense, zero-mismatch read.
 */
type TrackedThenable = PromiseLike<Record<string, unknown>> & {
  status: 'pending' | 'fulfilled' | 'rejected';
  value?: Record<string, unknown>;
  reason?: unknown;
};

const unknownKeyError = (key: string, keys: readonly string[]): Error =>
  new Error(
    `taujs: unknown deferred data key "${key}". This route declares [${keys.map((k) => `"${k}"`).join(', ')}]. ` +
      "Declared keys come from the route's `attr.deferred` record; the host does not validate reads.",
  );

const releasedError = (key: string): Error => new Error(`taujs: deferred data "${key}" was read after the response terminal; the holder has been released.`);

const ownKey = (source: object, key: string): boolean => Object.prototype.hasOwnProperty.call(source, key);

/**
 * Track a HOST-owned promise without mutating it: the registry is response-owned and frozen by
 * contract, so React's bookkeeping lives on our own wrapper, which only DELEGATES `then`. The
 * status handlers are attached HERE, before React attaches its retry ping, so the status is always
 * current by the time React re-reads it.
 */
const track = (promise: PromiseLike<Record<string, unknown>>): TrackedThenable => {
  const tracked: TrackedThenable = { status: 'pending', then: (onFulfilled, onRejected) => promise.then(onFulfilled, onRejected) };

  void promise.then(
    (value) => {
      if (tracked.status !== 'pending') return;
      tracked.status = 'fulfilled';
      tracked.value = value;
    },
    (reason) => {
      if (tracked.status !== 'pending') return;
      tracked.status = 'rejected';
      tracked.reason = reason;
    },
  );

  return tracked;
};

/** An ALREADY-SETTLED thenable we own outright: client seeding, and post-deadline server reads. */
const settled = (outcome: DeferredOutcome, key: string): TrackedThenable => {
  if (outcome.status === 'complete') {
    const promise = Promise.resolve(outcome.value);

    return { status: 'fulfilled', value: outcome.value, then: (f, r) => promise.then(f, r) };
  }

  const reason = new DeferredDataError(key, outcome.status);
  const promise = Promise.reject(reason);
  promise.catch(() => {}); // pre-observed: a boundary that is never rendered must stay harmless

  return { status: 'rejected', reason, then: (f, r) => promise.then(f, r) };
};

/**
 * @internal The per-request (server) / per-root (client) holder. `resource()` is a RENDER-PHASE
 * read returning the tracked thenable `use()` consumes, so the suspension is React's, not ours.
 */
export type DeferredHolder = {
  readonly keys: readonly string[];
  // A bare `PromiseLike`: React's `use()` overloads discriminate on a literal `status`, so the
  // tracked shape stays module-internal and is re-narrowed at the one site that reads it.
  resource: (key: string) => PromiseLike<Record<string, unknown>>;
  /**
   * The response-level deferred deadline (decision 18). LATCHES, so a read registering afterwards
   * is born `aborted` rather than starting a fresh unbounded wait, and returns how many CONSUMED
   * entries were still pending - the renderer abandons those through React's own `stream.abort`.
   */
  expire: () => number;
  /** Terminal: drop every retained value, promise and source reference. Idempotent. */
  release: () => void;
};

const createHolder = (keys: readonly string[], make: (key: string) => TrackedThenable, guard: (key: string) => void, onRelease: () => void): DeferredHolder => {
  const entries = new Map<string, TrackedThenable>();
  let released = false;
  let expired = false;

  return {
    keys,

    resource(key: string) {
      const existing = entries.get(key);
      if (existing) return existing;
      if (released) throw releasedError(key);
      guard(key);

      const entry = expired ? settled({ status: 'aborted' }, key) : make(key);
      entries.set(key, entry);

      return entry;
    },

    expire() {
      expired = true;
      let pending = 0;
      for (const entry of entries.values()) if (entry.status === 'pending') pending += 1;

      return pending;
    },

    release() {
      released = true;
      entries.clear();
      onRelease();
    },
  };
};

/**
 * @internal SERVER holder over the host's registry (renderer contract items 1, 7, 8).
 *
 * Entries are tracked LAZILY, on first read, so an unconsumed key is never observed here and never
 * counts towards the deadline - the host has already pre-observed every promise, so an unconsumed
 * rejection stays harmless.
 */
export const createDeferredHolder = (registry: DeferredDataRegistry): DeferredHolder => {
  let source: DeferredDataRegistry | undefined = registry;
  const keys = Object.freeze(Object.keys(registry));

  return createHolder(
    keys,
    (key) => track(source![key]!),
    (key) => {
      if (!source) throw releasedError(key);
      if (!ownKey(source, key)) throw unknownKeyError(key, keys);
    },
    () => {
      source = undefined;
    },
  );
};

/** @internal CLIENT holder over the private envelope. Every entry is already settled at creation. */
export const createHydrationHolder = (state: DeferredHydrationState): DeferredHolder => {
  const keys = Object.freeze(Object.keys(state));

  return createHolder(
    keys,
    (key) => settled(state[key]!, key),
    (key) => {
      if (!ownKey(state, key)) throw unknownKeyError(key, keys);
    },
    () => {},
  );
};

const DeferredDataContext = createContext<DeferredHolder | null>(null);

/** @internal Wiring, never an application surface (decision 10). */
export const DeferredDataProvider = ({ holder, children }: React.PropsWithChildren<{ holder: DeferredHolder }>) => (
  <DeferredDataContext.Provider value={holder}>{children}</DeferredDataContext.Provider>
);

const holderOrThrow = (accessor: string, key: string): DeferredHolder => {
  const holder = useContext(DeferredDataContext);
  if (!holder) {
    throw new Error(
      `taujs: ${accessor}("${key}") was called outside a deferred-data provider. ` +
        "Only a `render: 'streaming'` route that declares `attr.deferred` provides one.",
    );
  }

  return holder;
};

/**
 * THROWING read. Suspends the nearest `<Suspense>` while the entry is pending and throws into the
 * nearest error boundary when it failed or was aborted. An unknown key is a deterministic DEVELOPER
 * error naming the declared set - never a suspended boundary and never `undefined`.
 *
 * `react-dom/server` (Fizz) has NO server-side error boundaries: a rejected read errors the nearest
 * `<Suspense>`, which React hands to the client to render. That is React's native model, and it is
 * why {@link useDeferredDataResult} - not this read - is the path that completes the RESPONSE with
 * a handled fallback (decision 13).
 */
export function useDeferredData<T extends Record<string, unknown> = Record<string, unknown>>(key: string): T {
  return use(holderOrThrow('useDeferredData', key).resource(key)) as T;
}

/**
 * RESULT read - React's server-completing consumed-rejection path (decision 13).
 *
 * It still SUSPENDS natively while the entry is pending, then returns the outcome as a value, so an
 * application renders a handled fallback INTO the streamed document. `failed` and `aborted` carry
 * no value, message, stack or cause.
 */
export function useDeferredDataResult<T extends Record<string, unknown> = Record<string, unknown>>(key: string): DeferredResult<T> {
  // Read the tracked status FIRST rather than try/catching `use()`: React signals a suspension by
  // throwing an unexported internal sentinel, so a catch-based version would have to guess at
  // React's control flow. A still-pending entry falls through to `use()` and suspends natively;
  // React retries once it settles, and this same check then sees the rejection.
  const resource = holderOrThrow('useDeferredDataResult', key).resource(key) as TrackedThenable;

  if (resource.status === 'rejected') return { status: resource.reason instanceof DeferredDataError ? resource.reason.outcome : 'failed' };

  return { status: 'complete', value: use(resource as PromiseLike<T>) as T };
}

/**
 * The typed component-facing façade. `D` comes from the route config
 * (`DeferredDataOf<typeof route>`), so the key is checked and the payload type DERIVED - an
 * application never re-declares a payload shape:
 *
 * ```ts
 * const useDeferred = createDeferredAccessor<DeferredDataOf<typeof productRoute>>();
 * const reviews = useDeferred('reviews'); // typed from the route's serviceData() brand
 * ```
 *
 * A factory rather than a two-type-parameter hook on purpose: TypeScript cannot infer one type
 * argument while another is supplied explicitly, so `useDeferredData<D>('reviews')` would collapse
 * the return to a union over every declared key.
 */
export function createDeferredAccessor<D>() {
  return function useDeferred<K extends keyof D & string>(key: K): D[K] {
    return useDeferredData(key) as D[K];
  };
}

/**
 * @internal Read the private envelope ONCE, synchronously, in document order, and drop the carrier.
 *
 * An ABSENT carrier is the ordinary case - a route that declared nothing, and (decision 8)
 * `hydrate: false` - never an error and never a reason to fetch.
 */
export const takeDeferredHydrationState = (): DeferredHydrationState | undefined => {
  try {
    const w = window as unknown as Record<string, unknown>;
    const raw = w[DEFERRED_STATE_CARRIER];
    delete w[DEFERRED_STATE_CARRIER];

    if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return undefined;

    return raw as DeferredHydrationState;
  } catch {
    // A hostile or absent global must never break bootstrap.
    return undefined;
  }
};

// packages/solid/src/SSRDeferredData.ts
import { createResource, sharedConfig } from 'solid-js';

import { useSSRStore } from './SSRDataStore.js';
import { getDeferredData } from './internal.js';

import type { Accessor } from 'solid-js';

/**
 * RFC 0007 - the @taujs/solid deferred-data adapter. The point of this module is how LITTLE it
 * does: Solid already owns every mechanism the RFC asks a renderer for.
 *
 *  - `createResource` maps a promise onto a `<Suspense>` boundary and suspends THAT boundary only;
 *  - `renderToStream` emits its own `<template>` + `$df(...)` patch scripts for the late fragment,
 *    and its own serialised payload for hydration - τjs writes none of those bytes;
 *  - the client `createResource` reads that payload through Solid's own hydration context and never
 *    calls the fetcher, so hydration re-executes no loader by construction;
 *  - a rejected resource reaches the application's `<ErrorBoundary>` on the SERVER (decision 13:
 *    Solid's engine has real server-side error boundaries, so the throwing read is Solid's
 *    server-completing consumed-rejection path and no result accessor is needed) and crosses the
 *    wire through the package's non-disableable error sanitiser, so no server detail travels.
 *
 * So the adapter is a store-carried holder that turns a host promise into a Solid resource, plus
 * the ONE case Solid cannot express on its own: an entry still pending when the response terminated
 * (`aborted`). Solid's serialised slot for such a key is a promise that will never settle, so a
 * hydrating client would sit in its fallback forever; the envelope is what makes that deterministic.
 *
 * NO MEMOISATION, deliberately. A Solid `<Suspense>` re-runs its children when a resource settles,
 * with the hydration id counter reset, so a τjs-side per-key cache would consume a context id on
 * the FIRST pass and none on the second - shifting every id allocated after it and breaking
 * hydration for unrelated application resources. Calling `createResource` on every read keeps id
 * consumption identical in every pass and on the client; Solid itself dedupes by context id and
 * skips the fetcher once data is present, so "start once" is Solid's guarantee, not a cache of ours.
 *
 * EXPORT HYGIENE (renderer contract item 9 / decision 10): only `createDeferredAccessor`,
 * `useDeferredData`, `DeferredDataError` and the `DeferredAccessor` type reach `index.ts`.
 */

/** @internal The host's internal transport (`RenderOptions.deferredData`), structurally re-stated. */
export type DeferredDataRegistry = Readonly<Record<string, Promise<Record<string, unknown>>>>;

/** @internal RFC 0007 (R4): the only three v1 outcomes. `failed` carries NO message, stack or detail. */
export type DeferredOutcome = { status: 'complete'; value: Record<string, unknown> } | { status: 'failed' } | { status: 'aborted' };

/** @internal */
export type DeferredHydrationState = Readonly<Record<string, DeferredOutcome>>;

/** @internal The private, UNDOCUMENTED envelope carrier the host attaches at end of stream. */
export const DEFERRED_STATE_CARRIER = '__TAUJS_DEFERRED_STATE__';

/**
 * The terminal for a `failed` or `aborted` entry. It names the KEY and the OUTCOME and nothing
 * else - the key is route configuration already visible in the application's own source, so no
 * server value, message, stack or cause is constructible from it.
 */
export class DeferredDataError extends Error {
  readonly key: string;
  readonly outcome: 'failed' | 'aborted';

  constructor(key: string, outcome: 'failed' | 'aborted') {
    super(
      outcome === 'aborted' ? `taujs: deferred data "${key}" was abandoned when the response terminated` : `taujs: deferred data "${key}" failed on the server`,
    );
    this.name = 'DeferredDataError';
    this.key = key;
    this.outcome = outcome;
  }
}

/**
 * `T | undefined`, matching Solid's own `Resource<T>` exactly.
 *
 * Solid does NOT skip a suspended boundary's body: it runs once with the accessor returning
 * `undefined` (that is how the resource registers with the enclosing `<Suspense>`) and again when
 * the resource settles. Only the second pass reaches the wire, so the DELIVERED html always carries
 * the value - but the application must still write `reviews()?.count` or `<Show when={reviews()}>`,
 * exactly as for any other Solid resource. Typing this `Accessor<T>` would be a lie about the first
 * pass.
 */
export type DeferredAccessor<T> = Accessor<T | undefined>;

/** @internal */
export type DeferredDataHolder = {
  /** The declared key set for THIS request. Authoritative; an unknown read is a developer error. */
  readonly keys: readonly string[];
  /** Map a declared key onto a Solid accessor. Suspends the reading boundary only. */
  read<T>(key: string): DeferredAccessor<T>;
  /**
   * The response-level deferred deadline (decision 18). A LATCH, not a one-shot sweep:
   *
   *  1. every consumed entry that has not settled is abandoned NOW, by rejecting the ADAPTER'S OWN
   *     wrapper, so Solid errors those boundaries through its native channel and finishes the
   *     document itself;
   *  2. the holder stays expired, so a boundary whose FIRST read happens after the deadline is born
   *     abandoned rather than starting a fresh, unbounded wait.
   *
   * Without (2) the deadline would be a hint: a late-registering consumer is invisible to the timer.
   * The host's response-owned promise is NOT touched in either case - it stays pending, the host
   * classifies it `aborted` at its write site, and the service still observes the request signal.
   * Returns how many were abandoned by (1).
   */
  expire(): number;
  /** Release every reference this holder owns. Idempotent; runs on every terminal. */
  release(): void;
};

const hasOwn = (o: object, k: string): boolean => Object.prototype.hasOwnProperty.call(o, k);

const unknownKey = (key: string, keys: readonly string[]): Error =>
  new Error(`taujs: unknown deferred data key ${JSON.stringify(key)}. This route declares [${keys.map((k) => JSON.stringify(k)).join(', ')}].`);

const releasedError = (key: string): Error =>
  new Error(`taujs: deferred data ${JSON.stringify(key)} was read after the response terminal; the holder has been released.`);

/**
 * @internal SERVER holder. The registry is RESPONSE-OWNED: the promises are already started and
 * already pre-observed by the host, so nothing here starts, restarts, memoises or decorates them.
 */
export function createDeferredHolder(source: DeferredDataRegistry, onAbandon?: (keys: readonly string[]) => void): DeferredDataHolder {
  const keys = Object.freeze(Object.keys(source));
  const pending = new Set<string>();
  const wrappers = new Map<string, { promise: Promise<Record<string, unknown>>; abandon: (reason: unknown) => void }>();
  // The ONLY reference this adapter keeps to the response-owned registry, dropped at the terminal.
  let registry: DeferredDataRegistry | undefined = source;
  let released = false;
  let expired = false;

  /**
   * The adapter's own promise per key, created lazily on first read. It DELEGATES to the
   * response-owned promise and never mutates or replaces it - but because the adapter owns this
   * one, the deadline can settle it, which is the whole mechanism behind `expire()`. Memoising the
   * WRAPPER is safe (it consumes no hydration context id); memoising the RESOURCE would not be.
   */
  const wrapper = (key: string): Promise<Record<string, unknown>> => {
    const existing = wrappers.get(key);
    if (existing) return existing.promise;

    if (expired) {
      // The deadline already passed: abandon immediately and tell the renderer, rather than
      // starting a fresh unbounded wait on a document it is still holding open.
      const promise = Promise.reject(new DeferredDataError(key, 'aborted')) as Promise<Record<string, unknown>>;
      promise.catch(() => {}); // pre-observed: Solid may never consume this rejection
      wrappers.set(key, { promise, abandon: () => {} });
      onAbandon?.([key]);

      return promise;
    }

    let abandon!: (reason: unknown) => void;
    const promise = new Promise<Record<string, unknown>>((resolve, reject) => {
      abandon = reject;
      registry![key]!.then(
        (value) => {
          pending.delete(key);
          resolve(value);
        },
        (reason) => {
          pending.delete(key);
          reject(reason);
        },
      );
    });
    promise.catch(() => {}); // pre-observed: an abandoned wrapper must never be an unhandledRejection

    pending.add(key);
    wrappers.set(key, { promise, abandon });

    return promise;
  };

  return {
    keys,

    read<T>(key: string): DeferredAccessor<T> {
      if (released) throw releasedError(key);
      if (!registry || !hasOwn(registry, key)) throw unknownKey(key, keys);

      const [read] = createResource(() => wrapper(key));

      return read as unknown as DeferredAccessor<T>;
    },

    expire() {
      expired = true;

      const abandoned = [...pending];
      for (const key of abandoned) {
        pending.delete(key);
        wrappers.get(key)?.abandon(new DeferredDataError(key, 'aborted'));
      }
      if (abandoned.length > 0) onAbandon?.(abandoned);

      return abandoned.length;
    },

    release() {
      released = true;
      registry = undefined;
      pending.clear();
      wrappers.clear();
    },
  };
}

/**
 * @internal CLIENT holder, built from the envelope read synchronously at bootstrap.
 *
 * `complete` and `failed` are deliberately routed back through `createResource` rather than
 * short-circuited: during hydration Solid finds its own serialised slot and uses it WITHOUT calling
 * the fetcher, which is the native zero-refetch path. The fetcher below is the fallback for a
 * boundary Solid never serialised, and it too is refetch-free - it resolves from the envelope value
 * already in memory.
 *
 * `aborted` is the one case that must NOT reach Solid's slot: the server terminated with that
 * promise still pending, so the slot holds a promise nothing will ever settle and the boundary
 * would stay in its fallback forever. The context id is consumed anyway (so every later hydration
 * id still lines up with the server's walk) and the read throws into the app's `<ErrorBoundary>`.
 */
export function createHydrationHolder(source: DeferredHydrationState): DeferredDataHolder {
  const keys = Object.freeze(Object.keys(source));
  let envelope: DeferredHydrationState | undefined = source;
  let released = false;

  return {
    keys,

    read<T>(key: string): DeferredAccessor<T> {
      // The released check comes FIRST: `keys` is frozen at construction while `envelope` is
      // dropped by `release()`, so falling through to `unknownKey` would contradict itself.
      if (released) throw releasedError(key);
      if (!envelope || !hasOwn(envelope, key)) throw unknownKey(key, keys);

      const outcome = envelope[key]!;

      if (outcome.status === 'aborted') {
        // Burn the context id the SERVER's `createResource` consumed at this position; skipping it
        // would shift every subsequent id and break hydration for unrelated application resources.
        if (sharedConfig.context) sharedConfig.getNextContextId();

        return (() => {
          throw new DeferredDataError(key, 'aborted');
        }) as DeferredAccessor<T>;
      }

      const [read] = createResource<Record<string, unknown>>(() =>
        outcome.status === 'complete' ? Promise.resolve(outcome.value) : Promise.reject(new DeferredDataError(key, 'failed')),
      );

      return read as unknown as DeferredAccessor<T>;
    },

    // No request lifecycle to bound on the client: the outcomes are already terminal.
    expire: () => 0,

    release() {
      released = true;
      envelope = undefined;
    },
  };
}

/**
 * Read a declared deferred entry. ONE component, both sides - it never learns which side it is on.
 *
 * Reading a pending entry suspends the nearest `<Suspense>` and nothing else; a rejected entry
 * throws into the nearest `<ErrorBoundary>`, on the SERVER and on the client alike. PLACEMENT
 * MATTERS: the `<ErrorBoundary>` must sit INSIDE the `<Suspense>`; outside it the response still
 * completes and the rejection is still redacted, but the fallback renders on the client.
 */
export function useDeferredData<T>(key: string): DeferredAccessor<T> {
  const holder = getDeferredData(useSSRStore()) as DeferredDataHolder | undefined;

  if (!holder) {
    throw new Error(`taujs: useDeferredData(${JSON.stringify(key)}) requires a route declaring \`attr.deferred\`, rendered by the τjs Solid renderer`);
  }

  return holder.read<T>(key);
}

/**
 * The TYPED façade: `createDeferredAccessor<DeferredDataOf<typeof route>>()`.
 *
 * A factory rather than `useDeferredData<D>('reviews')` because TypeScript cannot infer one type
 * argument while another is supplied explicitly - a two-parameter hook collapses the return type to
 * a union over every declared key. The factory fixes `D` once and infers `K` from the argument.
 */
export function createDeferredAccessor<D>() {
  return <K extends keyof D & string>(key: K): DeferredAccessor<D[K]> => useDeferredData<D[K]>(key);
}

/**
 * @internal Read the private envelope ONCE and drop the carrier.
 *
 * An ABSENT carrier is the ordinary case - a route that declared nothing, and (decision 8)
 * `hydrate: false` - never an error and never a reason to fetch.
 */
export const takeDeferredHydrationState = (): DeferredHydrationState | undefined => {
  try {
    const w = window as unknown as Record<string, unknown>;
    const raw = w[DEFERRED_STATE_CARRIER];
    delete w[DEFERRED_STATE_CARRIER];

    if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return undefined;

    return raw as DeferredHydrationState;
  } catch {
    // A hostile or absent global must never break bootstrap.
    return undefined;
  }
};
